run:
  timeout: 1m

linters:
  enable:
    - gofmt
    - gosimple
    - revive
    - copyloopvar
    - unparam
    - govet
    - staticcheck

linters-settings:
issues:
  exclude-rules:
  exclude-dirs:
    - log