run:
  timeout: 1m

linters:
  enable:
    # - lll
    - gofmt
    - gosimple
    - revive
    - copyloopvar
    - unparam

linters-settings:
  # lll:
  #   line-length: 300

issues:
  exclude-rules:
    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
  exclude-dirs:
    - log