name: feeder-app-base

services:
  feeder-app:
    container_name: feeder-app
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    image: sambly/feeder-app:${FEEDER_APP_TAG:-latest}  
    volumes:
      - ./log:/app/log
    environment:
      ENVIRONMENT: docker
      FEEDER_HTTP_PORT_HEALTH: ${FEEDER_HTTP_PORT_HEALTH:-8080}     
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${FEEDER_DB_PASSWORD}
      MYSQL_DATABASE: ${FEEDER_DB_NAME}
    ports:
      - "${FEEDER_DB_PORT_HOST:-3307}:${FEEDER_DB_PORT:-3306}"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql --silent -u root -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 100s   
volumes:
  mysql_data: