version: '3.8'

services:
  feeder_app:
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        ENVIRONMENT: docker
        BUILD_TARGET: ${BUILD_TARGET:-exchange}
    volumes:
      - ./log:/app/log
    environment:
      ENVIRONMENT: docker
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT_HOST:-3307}:${DB_PORT:-3306}"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: